
//Register form actions
export const REGISTER_FORM_SUBMIT ='REGISTER_FORM_SUBMIT';
export const REGISTER_FORM_START ='REGISTER_FORM_START';
export const REGISTER_FORM_SUCCESS ='REGISTER_FORM_SUCCESS';
export const REGISTER_FORM_ERROR ='REGISTER_FORM_ERROR';

//Login form actions
export const LOGIN_FORM_SUBMIT ='LOGIN_FORM_SUBMIT';
export const LOGIN_FORM_START ='LOGIN_FORM_START';
export const LOGIN_FORM_SUCCESS ='LOGIN_FORM_SUCCESS';
export const LOGIN_FORM_ERROR ='LOGIN_FORM_ERROR';
